# only used in development!
version: '2'

services:
  fpm:
    build:
      context: backend
      dockerfile: Dockerfile
    image: blindern/intern-backend
    environment:
      LARAVEL_ENV: local
      APP_ENV: local
      APP_DEBUG: 1
      APP_KEY: KeNd439jeX9n9hqudOxXqCQErFmbApoi
      DB_MONGODB_HOST: database
      DB_MONGODB_PORT: 27017
      DB_MONGODB_DATABASE: intern
      DB_MONGODB_USERNAME:
      DB_MONGODB_PASSWORD:
      LARAVEL_SESSION_SECURE: 0
      INTERN_USERS_API_KEY: $INTERN_USERS_API_KEY
    volumes:
     - ./backend/:/var/www/html/
    command: /dev.sh
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
      #- ./:/var/www/html/
    command: nginx -g 'daemon off;'
  database:
    image: mongo
    volumes:
      - db:/data/db/
    environment:
      MONGO_INITDB_ROOT_USERNAME: intern
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "127.0.0.1:27017:27017"

volumes:
  db:
