# only used in development!
version: '2'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: blindern/intern-backend
    environment:
      LARAVEL_ENV: local
      APP_ENV: local
      APP_DEBUG: 1
      APP_KEY: KeNd439jeX9n9hqudOxXqCQErFmbApoi
      DB_MONGODB_HOST: database
      DB_MONGODB_PORT: 27017
      DB_MONGODB_DATABASE: intern
      DB_MONGODB_USERNAME: intern
      DB_MONGODB_PASSWORD: secret
      LARAVEL_SESSION_SECURE: 0
      INTERN_USERS_API_KEY: $INTERN_USERS_API_KEY
      PRINTERDB_DSN: pgsql:host=postgresql-1.zt.foreningenbs.no;dbname=pykota
      PRINTERDB_USERNAME: $PRINTERDB_USERNAME
      PRINTERDB_PASSWORD: $PRINTERDB_PASSWORD
    ports:
      - "8081:80"
  database:
    image: mongo
    volumes:
      - db:/data/db/
    environment:
      MONGO_INITDB_ROOT_USERNAME: intern
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "127.0.0.1:27017:27017"

volumes:
  db:
